WEB-APP/Controllers/AdminController.cs
using EmWebApp.BLL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using EmWebApp.Data;

namespace EmWebApp.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {        
        // GET: Admin
        public ActionResult Index(string passportNumber, DateTime? appointmentDate)
        {
            List<ConsularApptVM> list = EmbassyAppDb.GetConsularApptsAdmin(passportNumber, appointmentDate);
            if (list.Count > 0)
            {
                ViewBag.DownloadCsv = true;
                ViewBag.PassportNumber = passportNumber;
                ViewBag.AppointmentDate = appointmentDate;
            }
            else
            {
                ViewBag.DownloadCsv = false;
            }

            return View(list);
        }

        public ActionResult GetCSV(string ppNum, DateTime? apptDt)
        {
            List<ConsularApptVM> list = EmbassyAppDb.GetConsularApptsAdmin(ppNum, apptDt);
            if (list.Count <= 0)
                return new EmptyResult();

            string csvString = EmbassyAppDb.GetConsularApptsAdminCSV(list, ',');
            string csvFileName = String.Format("Appointments_{0}{1}.csv", apptDt == null ? "All" : apptDt.Value.ToString("yyyyMMdd"), string.IsNullOrEmpty(ppNum) ? string.Empty : ppNum);

            return File(new System.Text.UTF8Encoding().GetBytes(csvString), "text/csv", csvFileName);
        }
        

        // GET: Admin/PrintApptLtr/5
        public ActionResult PrintApptLtr(int id)
        {
            ConsularApptVM model = EmbassyAppDb.GetConsularApptById(id);

            AppointmentType appointmentType = ConsularAppointmentTypes.GetAppointmentType(model.AppointmentType);
            string pdfTemplateFile = ConfirmationLetterPdf.GetPdfTemplateFileName(appointmentType, model.StayType);
            MemoryStream pdfStream = ConfirmationLetterPdf.GetAppointmentLetterStream(pdfTemplateFile, model);

            //string confirmationLetter = this.GetConfirmationLetter(id);
            //MemoryStream pdfStream = new MemoryStream();
            //Pdf.WriteHtmlToPdfStream(confirmationLetter, pdfStream);

            return new FileStreamResult(pdfStream, "application/pdf");
        }

        // GET: ConsularAppt/Details/5
        public ActionResult Details(int id)
        {
            ConsularApptVM model = EmbassyAppDb.GetConsularApptById(id);
            AppointmentType appointmentType = ConsularAppointmentTypes.GetAppointmentType(model.AppointmentType);
            ViewBag.AppointmentType = appointmentType.Description;

            return View(model);
        }
    }    
}

WEB-APP/Controllers/ConsularApptController.cs
using EmWebApp.BLL;
using EmWebApp.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Mail;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web.Mvc;
using EmWebApp.Data;

namespace EmWebApp.Controllers
{
    public class ConsularApptController : Controller
    {
        // GET: ConsularAppt/Create
        public ActionResult Create()
        {
            ViewBag.Title = "Embassy Consular Appointment Form";
            if (Request.IsAuthenticated)
                ViewBag.Title = "Embassy Consular Appointment Form (Admin)";

            if (EmWebAppConfig.PrefilledFormTest)
                return View(CATestData.GetNewAppt());            

            return View(new ConsularApptVM());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AppointmentDate,AppointmentType,Name,Gender,DateOfBirth,PlaceOfBirth,Nationality,NRIC_No,PassportNumber,PassportIssuedDate,ConsulateLocation,StayType,StayPermitNumber,EmployerName,Occupation,ContactAddr1,ContactAddr2,ContactPhone,ContactEmail,HomeAddr1,HomeAddr2,HomePhone,Note")] ConsularApptVM consularApptVM)
        {
            if (!Request.IsAuthenticated)
            {
                ViewBag.Title = "Embassy Consular Appointment Form";
                EmbassyAppDb.AddConsularAppt(consularApptVM, EmWebAppConfig.QueueNumberInitial);

                Email email = this.GetConfirmationRequestEmail(consularApptVM);
                using (var smtp = new SmtpClient())
                {
                    smtp.Prep();
                    await smtp.SendMailAsync(email.Message);
                }

                ViewBag.PartialHtml = "_MsgApptReceived";
            }
            else
            {
                ViewBag.Title = "Embassy Consular Appointment Form (Admin)";
                consularApptVM.Note = "[ADMIN]" + consularApptVM.Note;
                EmbassyAppDb.AddConsularAppt(consularApptVM, EmWebAppConfig.QueueNumberInitial);
                DateTime? confirmedApptDate = null;
                int? confirmedQueNumber = 0;
                ConsularApptVM consularApptVM2 = EmbassyAppDb.ConfirmConsularAppt(consularApptVM.Id, consularApptVM.ActivationCode, ref confirmedApptDate, ref confirmedQueNumber);

                consularApptVM.QueueNumber = confirmedQueNumber.GetValueOrDefault();

                ViewBag.PartialHtml = "_MsgApptConfirmedByAdmin";
            }

            AppointmentType appointmentType = ConsularAppointmentTypes.GetAppointmentType(consularApptVM.AppointmentType);
            ViewBag.AppointmentType = appointmentType.Description;

            return View(consularApptVM);
        }

        // GET: ConsularAppt
        [Authorize]  /* For Testing Prefilled Forms */
        public ActionResult Index()
        {
            ViewBag.Title = "Embassy Consular Appointment Form (Admin)";
            ConsularApptVM ca = CATestData.GetNewAppt();
            return View(ca);
        }

        [Authorize]  /* For Testing Prefilled Forms */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "AppointmentDate,AppointmentType,Name,Gender,DateOfBirth,PlaceOfBirth,Nationality,NRIC_No,PassportNumber,PassportIssuedDate,ConsulateLocation,StayType,StayPermitNumber,EmployerName,Occupation,ContactAddr1,ContactAddr2,ContactPhone,ContactEmail,HomeAddr1,HomeAddr2,HomePhone,Note")] ConsularApptVM consularApptVM)
        {
            if (!ModelState.IsValid)
                this.LogModelStateError();

            ViewBag.Title = "Embassy Consular Appointment Form (Admin)";

            consularApptVM.Note = "[ADMIN]" + consularApptVM.Note;
            EmbassyAppDb.AddConsularAppt(consularApptVM, EmWebAppConfig.QueueNumberInitial);

            DateTime? confirmedApptDate = null;
            int? confirmedQueNumber = 0;
            ConsularApptVM consularApptVM2 = EmbassyAppDb.ConfirmConsularAppt(consularApptVM.Id, consularApptVM.ActivationCode, ref confirmedApptDate, ref confirmedQueNumber);

            consularApptVM.QueueNumber = confirmedQueNumber.GetValueOrDefault();

            ViewBag.PartialHtml = "_MsgApptConfirmedByAdmin";

            AppointmentType appointmentType = ConsularAppointmentTypes.GetAppointmentType(consularApptVM.AppointmentType);
            ViewBag.AppointmentType = appointmentType.Description;

            return View(consularApptVM);
        }

        // GET: ConsularAppt/Confirmed/5
        [HttpGet]
        public ActionResult Confirmed(int id, string code)
        {
            ViewBag.ConfirmedId = id;
            ViewBag.ConfirmedCode = code;
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> ConfirmPosted(string confirmedId, string confirmedCode)
        {
            if (!Request.IsAjaxRequest())
                return Content("Request Error.");

            int id = int.Parse(confirmedId);
            string code = confirmedCode;

            DateTime? confirmedApptDate = null;
            int? confirmedQueNumber = 0;
            ConsularApptVM consularApptVM = EmbassyAppDb.ConfirmConsularAppt(id, code, ref confirmedApptDate, ref confirmedQueNumber);
            if (consularApptVM == null)
            {
                return RedirectToAction("Error");
            }

            string confirmedEmailBody = this.GetConfirmedEmailBody(consularApptVM);
            string confirmationLetter = this.GetConfirmationLetter(consularApptVM);
            // To do: Maybe convert the confirmationLetter to PDF, or get fillable PDF letter 

            // Get Required Form Attachment List
            AppointmentType appointmentType = ConsularAppointmentTypes.GetAppointmentType(consularApptVM.AppointmentType);
            List<BLL.Attachment> formAttachments = appointmentType.Attachments?.List;

            // Start preparing for Email
            Email embassyMail = new Email
            {
                From = EmWebAppConfig.EmailAddress,
                DisplayName = EmWebAppConfig.EmailUser,
                To = consularApptVM.ContactEmail,
                Subject = EmWebAppConfig.EmailSubj_Confirmed,
                Body = confirmedEmailBody,
                IsHtml = true
            };

            // using (MemoryStream ms = new MemoryStream())
            string pdfTemplateFile = ConfirmationLetterPdf.GetPdfTemplateFileName(appointmentType, consularApptVM.StayType);
            using (MemoryStream ms = ConfirmationLetterPdf.GetAppointmentLetterStream(pdfTemplateFile, consularApptVM))
            using (MailMessage mailMsg = embassyMail.Message)
            using (var smtp = new SmtpClient())
            {

                System.Net.Mail.Attachment coverLetterPdf = Email.GetPdfAttachmentFromPdfStream(ms, "AppointmentLetter.pdf");
                // System.Net.Mail.Attachment coverLetterPdf = Email.GetPdfAttachmentFromHtmlString(confirmationLetter, ms, "AppointmentLetter.pdf");
                mailMsg.Attachments.Add(coverLetterPdf);

                if (formAttachments != null)
                {
                    foreach (var attachment in formAttachments)
                    {
                        if (System.IO.File.Exists(attachment.FullPath))
                        {
                            var emailAttachment = new System.Net.Mail.Attachment(attachment.FullPath, new ContentType(MediaTypeNames.Application.Pdf));
                            mailMsg.Attachments.Add(emailAttachment);
                        }
                    }
                }

                smtp.Prep();
                await smtp.SendMailAsync(mailMsg);
                // return View(consularApptVM);
                return PartialView("_MsgApptConfirmed", consularApptVM);
            }
        }
    }

}

WEB-APP/Views/ConsularAppt/Confirmed.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM

@{
    ViewBag.Title = "Consular Appointment Request - Confirmed";
}
<div id="updateTargetDiv">
    <center>
        <span class="glyphicon glyphicon-refresh spinning"></span> ...Processing ...
    </center>
</div>

@using (Ajax.BeginForm("ConfirmPosted", "ConsularAppt", new { },
                        new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "updateTargetDiv" },
                        new { id = "AjaxConfirmedForm" }))

{
    <input type="hidden" name="confirmedId" value="@ViewBag.ConfirmedId" />
    <input type="hidden" name="confirmedCode" value="@ViewBag.ConfirmedCode" />
}

@section Scripts {    

    <script type="text/javascript">

        $(function () {
            var $form = $("form[id='AjaxConfirmedForm']");
            var $target = $($form.attr("data-ajax-update"));
            var options = {
                url: $form.attr("action"),
                type: $form.attr("method"),
                data: $form.serialize(),
                error: function () {
                    $target.html("Error");
                }
            }
            $.ajax(options).done(function (data) {
                $target.replaceWith(data);
            });
            return false;
        });

    </script>

}

WEB-APP/Views/ConsularAppt/Create.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM
<div>
    @if (Model.Id > 0)
    {
        @Html.Partial((String)@ViewBag.PartialHtml, Model)
    }
    else
    {
        @Html.Partial("_ConsularApptForm", Model)
    }
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")

}

WEB-APP/Views/ConsularAppt/Delete.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConsularApptVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AppointmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointmentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QueueNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueueNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassportNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassportNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassportIssuedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassportIssuedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsulateLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsulateLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StayPermitNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StayPermitNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NRIC_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NRIC_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactAddr1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactAddr1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactAddr2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactAddr2)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddr1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddr1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddr2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddr2)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppointmentStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointmentStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WEB-APP/Views/ConsularAppt/Index.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM
<div>
    @if (Model.Id > 0)
    {
		@Html.Partial((String)@ViewBag.PartialHtml, Model)
	}
	else
	{
        @Html.Partial("_ConsularApptForm", Model);
    }
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")

}

WEB-APP/Views/ConsularAppt/_Address.cshtml
<!-- styles are defined in site.css -->
<div class="parent" style="padding:20px">
    <div class="left" style="text-align:left">
        <br /><b style="padding-bottom:10px">Myanmar Embassy</b>
        <br />No. 15, St. Martin's Drive, Singapore 257996
        <br />Tel: (65) 6735 5263, 6735 6576
        <br />Fax: (65) 6735 6236
        <br />Consular Section: (65) 6735 2035
        <br />
        <br /><strong>Email: </strong><a href="mailto:webmaster@myanmarembassy.sg">webmaster@myanmarembassy.sg</a>
    </div>
    <div class="center"  style="text-align:left">
        <br /><b style="padding-bottom:10px">Consular Office Hours:</b>
        <br />Application Time (08:00 AM - 12:00 PM)
        <br />Collection Time  (03:00 PM - 04:00 PM)
    </div>
    <div class="right" style="text-align:left">
    </div>
    <div style="clear:both;"></div>
</div>

WEB-APP/Views/ConsularAppt/_ApptFormDetails.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM
<br />
<center>
    <table frame="box" cellspacing="2" cellpadding="5" bgcolor="#ffffff">
        <tr>
            <td><div>Appointment Date: </div></td>
            <td><div><b>@(Model.AppointmentDate?.ToString("MMMM d, yyyy  [dddd]"))</b></div></td>
        </tr>
        <tr>
            <td><div>Queue Number: </div></td>
            <td><div><b>@Model.QueueNumber</b></div></td>

        </tr>
        <tr>
            <td><div>Appointment Type: </div></td>
            <td><div><b>@ViewBag.AppointmentType</b></div></td>
        </tr>
    </table>
</center>
<br />

<table margin="5" cellspacing="2" cellpadding="2" bgcolor="ffffff">

    <tr>
        <td style="background:#;"><div>Name: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.Name</b></div></td>
        <td style="background:#;"><div>Gender: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@(Model.Gender=="M"?"Male":"Female")</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>Date of Birth: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@(Model.DateOfBirth?.ToString("MMMM d, yyyy"))</b></div></td>
        <td style="background:#;"><div>Place of Birth: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.PlaceOfBirth</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>Nationality: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>Myanmar</b></div></td>
        <td style="background:#;"><div>Passport Number: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.PassportNumber</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>Psprt. Issue Date: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@(Model.PassportIssuedDate?.ToString("MMMM d, yyyy"))</b></div></td>
        <td style="background:#;"><div>NRIC Number: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.NRIC_No</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>Sgp.IC/Permit No: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.StayPermitNumber</b></div></td>
        <td style="background:#;"><div>Contact Email: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.ContactEmail</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>Company Name: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.EmployerName</b></div></td>
        <td style="background:#;"><div>Occupation: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.Occupation</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>(Sgp.) Address Line 1: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.ContactAddr1</b></div></td>
        <td style="background:#;"><div>(Sgp.) Address Line 2: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.ContactAddr2</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>Contact Phone: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.ContactPhone</b></div></td>
        <td style="background:#;"><div>(MM) Address Line 1: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.HomeAddr1</b></div></td>
    </tr>
    <tr>
        <td style="background:#;"><div>(MM) Address Line 2: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.HomeAddr2</b></div></td>
        <td style="background:#;"><div>(MM) Phone: </div></td>
        <td style="background:#ffffff;"><div style="padding-left:15px"><b>@Model.HomePhone</b></div></td>
    </tr>
</table>

WEB-APP/Views/ConsularAppt/_MsgApptConfirmed.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM
<br />
<div class="embassypaperbg">
    <div class="embassypaper">
        <p>
            <h4><strong>The consular appointment is confirmed.</strong></h4><br />
            <center>
                <table border=0 frame="box" cellspacing="2" cellpadding="5" bgcolor="#ffffff">
                    <tr>
                        <td style="background:#eeeeee;"><div>Name: </div></td>
                        <td style="background:#ffffff;"><div>@Model.Name</div></td>
                    </tr>
                    <tr>
                        <td style="background:#eeeeee;"><div>Passport Number: </div></td>
                        <td style="background:#ffffff;"><div>@Model.PassportNumber</div></td>
                    </tr>
                    <tr>
                        <td style="background:#eeeeee;"><div>Service Type: </div></td>
                        <td style="background:#ffffff;"><div>@ViewBag.AppointmentType</div></td>
                    </tr>
                    <tr>
                        <td style="background:#eeeeee;"><div>Appointment Date: </div></td>
                        <td style="background:#ffffff;"><div><b>@(Model.AppointmentDate?.ToString("MMMM d, yyyy  [dddd]"))</b></div></td>
                    </tr>
                    <tr>
                        <td style="background:#eeeeee;"><div>Queue Number: </div></td>
                        <td style="background:#ffffff;"><div>@Model.QueueNumber</div></td>
                    </tr>
                    <tr>
                        <td style="background:#eeeeee;"><div>Appointment Status: </div></td>
                        <td style="background:#ffffff;"><span style="background:#b6ff00; padding:5px;"><b>&nbsp;Confirmed&nbsp;</b></span></td>
                    </tr>
                </table>
            </center>
            <br /><br />
        </p>
        <p>
            We have sent an email with comfirmation letter and the required documents attached to your email: <strong>@Model.ContactEmail</strong>.
            <br /><br />
            Please review the required document list, print out the confirmation letter and bring it along with all other required documents with you on the appointment date.
        </p>
    </div>
</div>
<br /><br /><br />
<br /><br /><br />

WEB-APP/Views/ConsularAppt/_MsgApptConfirmedByAdmin.cshtml
@using EmWebApp.Data
@model EmWebApp.Data.ConsularApptVM
<br />
<div class="embassypaperbg">
	<div class="embassypaper">
		<p>
			<h4><strong>The consular appointment is confirmed.</strong></h4><br />
			<center>
				<table border=0 frame="box" cellspacing="2" cellpadding="5" bgcolor="#ffffff">
					<tr>
						<td style="background:#eeeeee;"><div>Name: </div></td>
						<td style="background:#ffffff;"><div>@Model.Name</div></td>
					</tr>
					<tr>
						<td style="background:#eeeeee;"><div>Passport Number: </div></td>
						<td style="background:#ffffff;"><div>@Model.PassportNumber</div></td>
					</tr>
					<tr>
						<td style="background:#eeeeee;"><div>Service Type: </div></td>
						<td style="background:#ffffff;"><div>@ViewBag.AppointmentType</div></td>
					</tr>
					<tr>
						<td style="background:#eeeeee;"><div>Appointment Date: </div></td>
						<td style="background:#ffffff;"><div><b>@(Model.AppointmentDate?.ToString("MMMM d, yyyy  [dddd]"))</b></div></td>
					</tr>
					<tr>
						<td style="background:#eeeeee;"><div>Queue Number: </div></td>
						<td style="background:#ffffff;"><div>@Model.QueueNumber</div></td>
					</tr>
					<tr>
						<td style="background:#eeeeee;"><div>Appointment Status: </div></td>
						<td style="background:#ffffff;"><span style="background:#b6ff00; padding:5px;"><b>&nbsp;Confirmed&nbsp;</b></span></td>
					</tr>
				</table>
				<br />
				@Html.ActionLink("Appointment Letter", "PrintApptLtr", "Admin", new { id = @Model.Id }, new { @class = "btn btn-default btn-sm", role = "button" })
			</center>
			<br /><br />
		</p>
		<p>
			This appointment is confirmed by Administrator: <strong>@HttpContext.Current.User.Identity.Name</strong>.
			<br /><br />
		</p>
	</div>
</div>
<br /><br /><br />
<br /><br /><br />